language: sh
script:
  - time bash bin/shpec -f 1 shpec/shpec_shpec.sh
  - time dash bin/shpec -f 1 shpec/shpec_shpec.sh
  - time ksh  bin/shpec -f 1 shpec/shpec_shpec.sh
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ksh
