language: sh
env:
  matrix:
    - LINT=true
    - SHELL=mksh
    - SHELL=bash
    - SHELL=dash
    - SHELL=ksh
    - SHELL=zsh
matrix:
  fast_finish: true
  allow_failures:
    - env: SHELL=zsh
script:
  - |
    ${LINT:-false} &&
      exec shellcheck -s sh bin/shpec  # `sh` refers to POSIX
    $SHELL bin/shpec shpec/shpec_shpec.sh
cache: apt
before_install:
  - |
    set -e -u
    get_shellcheck() {
      (
      for v 
      do
        pkg=shellcheck_${v}_amd64.deb
        url="http://ftp.debian.org/debian/pool/main/s/shellcheck/"
        wget $url/$pkg > /dev/null 2>& 1 || continue
        echo $pkg 
        break
      done
      )
    }
    if ${LINT:-false}; then
      pkg=$( get_shellcheck 0.3.7-1 0.3.5-3 0.3.4-3 )
      sudo dpkg -i $pkg && echo ok || echo no $?
    fi
    if ! type $SHELL > /dev/null; then
        sudo apt-get update -qq &&
        sudo apt-get install -y $SHELL
    fi
    $SHELL -c : && echo $SHELL ok
